dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2

branches:
  only:
    - /^master/

before_install:
  - cd $TRAVIS_BUILD_DIR
  - composer install

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)